apiVersion: skaffold/v2alpha3
kind: ConfigMap
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketapp-308317
  artifacts:
    # - image: us.gcr.io/ticketapp-308317/auth
    - image: nikitalipin97/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './src/**/*.ts'
            dest: .

    - image: nikitalipin97/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './src/**/*.js'
            dest: .


